import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import { FEATURED_LICHESS_BROADCAST, LICHESS_BROADCAST_SCHEMA, validateLichessBroadcast, lichessBroadcastStatus } from '../js/lichess-broadcasts-config.js';
import { LICHESS_BROADCAST_SANDBOX } from '../js/lichess-broadcasts-parent.js';
const read = path => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const invalid = changes => ({ ...FEATURED_LICHESS_BROADCAST, ...changes });

test('immutable featured event validates exact Lichess tournament-level URLs and provenance', () => {
  assert.equal(LICHESS_BROADCAST_SCHEMA, 'CaissaFeaturedExternalTournament.LichessBroadcast@1.0.0'); assert.ok(Object.isFrozen(FEATURED_LICHESS_BROADCAST)); assert.equal(validateLichessBroadcast(FEATURED_LICHESS_BROADCAST).ok, true);
  assert.equal(FEATURED_LICHESS_BROADCAST.frameUrl, 'https://lichess.org/embed/broadcast/gct-sinquefield-cup-2026/2sMqschv'); assert.equal(FEATURED_LICHESS_BROADCAST.organizerName, 'Grand Chess Tour'); assert.equal(FEATURED_LICHESS_BROADCAST.eventTimezone, 'America/Chicago');
});
test('validation fails closed for schema, fields, URL injection, credentials, ports, query, fragments, and schedule', () => {
  for (const candidate of [invalid({schema:'x'}),invalid({enabled:false}),invalid({extra:true}),invalid({displayName:'<script>'}),invalid({frameUrl:'http://lichess.org/embed/broadcast/gct-sinquefield-cup-2026/2sMqschv'}),invalid({frameUrl:'https://evil.test/embed/broadcast/gct-sinquefield-cup-2026/2sMqschv'}),invalid({frameUrl:'https://user:x@lichess.org/embed/broadcast/gct-sinquefield-cup-2026/2sMqschv'}),invalid({frameUrl:'https://lichess.org:444/embed/broadcast/gct-sinquefield-cup-2026/2sMqschv'}),invalid({frameUrl:FEATURED_LICHESS_BROADCAST.frameUrl+'?x=1'}),invalid({frameUrl:FEATURED_LICHESS_BROADCAST.frameUrl+'#x'}),invalid({providerEventUrl:'https://lichess.org/broadcast/other/2sMqschv'}),invalid({endsAt:FEATURED_LICHESS_BROADCAST.startsAt}),invalid({eventTimezone:'Mars/Base'})]) assert.equal(validateLichessBroadcast(candidate).ok, false);
});
test('status uses exact UTC boundaries without claiming live play', () => { const start=Date.parse(FEATURED_LICHESS_BROADCAST.startsAt),end=Date.parse(FEATURED_LICHESS_BROADCAST.endsAt); assert.equal(lichessBroadcastStatus(FEATURED_LICHESS_BROADCAST,start-1),'upcoming'); assert.equal(lichessBroadcastStatus(FEATURED_LICHESS_BROADCAST,start),'coverage-window'); assert.equal(lichessBroadcastStatus(FEATURED_LICHESS_BROADCAST,end),'completed'); assert.equal(lichessBroadcastStatus(FEATURED_LICHESS_BROADCAST,start,'unavailable'),'unavailable'); });
test('preserved controller remains frame-only, query-independent, and bounded', () => { const own=read('js/lichess-broadcasts-parent.js')+read('js/lichess-broadcasts-config.js'); assert.equal(LICHESS_BROADCAST_SANDBOX,'allow-scripts allow-same-origin'); assert.match(own,/createFrame\(\{ restoreFocus: true \}\)/); assert.match(own,/status\.focus\(\{ preventScroll: true \}\)/); assert.doesNotMatch(own,/fetch\(|XMLHttpRequest|WebSocket|EventSource|setInterval|postMessage|location\.search|URLSearchParams|frame\.focus|next\.focus/); });
test('standalone route is retired while reusable modules remain available for future Chess TV work', () => { const vercel=JSON.parse(read('vercel.json')); assert.ok(vercel.redirects.some(x=>x.source==='/watch/lichess-broadcasts'&&x.destination==='/watch/live-tournaments'&&x.permanent)); assert.equal(vercel.rewrites.some(x=>x.source==='/watch/lichess-broadcasts'),false); assert.doesNotMatch(read('js/caissa-primary-navigation.js'),/id: 'lichess-broadcasts'/); assert.doesNotMatch(read('public/sitemap.xml'),/\/watch\/lichess-broadcasts<\/loc>/); assert.match(read('docs/integrations/LICHESS_BROADCAST_EMBED_AUDIT.md'),/modules remain intentionally preserved/); });
