import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import vm from 'node:vm';
import { load } from 'cheerio';
import { FEATURED_LICHESS_BROADCAST, LICHESS_BROADCAST_SCHEMA, validateLichessBroadcast, lichessBroadcastStatus } from '../js/lichess-broadcasts-config.js';
import { LICHESS_BROADCAST_SANDBOX } from '../js/lichess-broadcasts-parent.js';
const read = path => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const invalid = changes => ({ ...FEATURED_LICHESS_BROADCAST, ...changes });

test('immutable featured event validates exact Lichess tournament-level URLs and provenance', () => {
  assert.equal(LICHESS_BROADCAST_SCHEMA, 'CaissaFeaturedExternalTournament.LichessBroadcast@1.0.0'); assert.ok(Object.isFrozen(FEATURED_LICHESS_BROADCAST)); assert.equal(validateLichessBroadcast(FEATURED_LICHESS_BROADCAST).ok, true);
  assert.equal(FEATURED_LICHESS_BROADCAST.frameUrl, 'https://lichess.org/embed/broadcast/gct-sinquefield-cup-2026/2sMqschv'); assert.equal(FEATURED_LICHESS_BROADCAST.organizerName, 'Grand Chess Tour'); assert.equal(FEATURED_LICHESS_BROADCAST.eventTimezone, 'America/Chicago');
});
test('validation fails closed for schema, fields, URL injection, credentials, ports, query, fragments, and schedule', () => {
  for (const candidate of [invalid({schema:'x'}),invalid({enabled:false}),invalid({extra:true}),invalid({displayName:'<script>'}),invalid({frameUrl:'http://lichess.org/embed/broadcast/gct-sinquefield-cup-2026/2sMqschv'}),invalid({frameUrl:'https://evil.test/embed/broadcast/gct-sinquefield-cup-2026/2sMqschv'}),invalid({frameUrl:'https://user:x@lichess.org/embed/broadcast/gct-sinquefield-cup-2026/2sMqschv'}),invalid({frameUrl:'https://lichess.org:444/embed/broadcast/gct-sinquefield-cup-2026/2sMqschv'}),invalid({frameUrl:FEATURED_LICHESS_BROADCAST.frameUrl+'?x=1'}),invalid({frameUrl:FEATURED_LICHESS_BROADCAST.frameUrl+'#x'}),invalid({providerEventUrl:'https://lichess.org/broadcast/other/2sMqschv'}),invalid({endsAt:FEATURED_LICHESS_BROADCAST.startsAt}),invalid({eventTimezone:'Mars/Base'})]) assert.equal(validateLichessBroadcast(candidate).ok, false);
});
test('status uses exact UTC boundaries without claiming live play', () => { const start=Date.parse(FEATURED_LICHESS_BROADCAST.startsAt),end=Date.parse(FEATURED_LICHESS_BROADCAST.endsAt); assert.equal(lichessBroadcastStatus(FEATURED_LICHESS_BROADCAST,start-1),'upcoming'); assert.equal(lichessBroadcastStatus(FEATURED_LICHESS_BROADCAST,start),'coverage-window'); assert.equal(lichessBroadcastStatus(FEATURED_LICHESS_BROADCAST,end),'completed'); assert.equal(lichessBroadcastStatus(FEATURED_LICHESS_BROADCAST,start,'unavailable'),'unavailable'); });
test('page owns exact SEO, no static frame, focused CSP, fallback, and independent attribution', () => { const html=read('lichess-broadcasts.html'),page=load(html); assert.equal(page('title').text(),'Watch Lichess Broadcasts | CAISSA Chess'); assert.equal(page('link[rel=canonical]').attr('href'),'https://www.caissa-chess.org/watch/lichess-broadcasts'); assert.equal(page('h1').length,1); assert.equal(page('iframe').length,0); assert.equal(page('meta[name=keywords]').length,0); assert.doesNotMatch(page('meta[name=robots]').attr('content'),/noindex/i); assert.match(page('meta[http-equiv="Content-Security-Policy"]').attr('content'),/frame-src https:\/\/lichess\.org;/); assert.match(page('.lichess-broadcasts-disclosure').text(),/independent credited gateway/); assert.match(page('main').text(),/does not guarantee that a game is in progress/); assert.equal(LICHESS_BROADCAST_SANDBOX,'allow-scripts allow-same-origin'); });
test('Retry owns one persistent programmatic focus target outside the iframe', () => { const page=load(read('lichess-broadcasts.html')),source=read('js/lichess-broadcasts-parent.js'); const target=page('[data-lichess-broadcasts-event-status][role="status"]'); assert.equal(target.length,1); assert.equal(target.attr('tabindex'),'-1'); assert.equal(page('[data-lichess-broadcasts-event-status][tabindex="0"]').length,0); assert.match(source,/createFrame\(\{ restoreFocus: true \}\)/); assert.match(source,/status\.focus\(\{ preventScroll: true \}\)/); assert.doesNotMatch(source,/frame\.focus|next\.focus/); });
test('runtime is frame-only, query-independent, and isolated from every other gateway', () => { const own=read('js/lichess-broadcasts-parent.js')+read('js/lichess-broadcasts-config.js'); assert.doesNotMatch(own,/fetch\(|XMLHttpRequest|WebSocket|EventSource|setInterval|postMessage|location\.search|URLSearchParams/); for(const file of ['index.html','yahoo-classic.html','playchess.html','fritz.html','tactics.html','live-blitz.html','live-tournaments.html','game-replayer.html','interactive-diagrams.html','lichess-tv.html']) assert.doesNotMatch(read(file),/data-lichess-broadcasts-frame|lichess-broadcasts-parent|embed\/broadcast\/gct-sinquefield/i,file); });
test('canonical route, nav successor, sitemap, and generated inventory own the destination once', () => { const window={}; vm.runInNewContext(read('js/caissa-primary-navigation.js'),{window,document:{querySelectorAll:()=>[]}}); const nav=window.CaissaPrimaryNavigation; assert.equal(nav.contractId,'CaissaGlobalNavigationOrderPolicy@1.12.0'); assert.deepEqual(Array.from(nav.inventory.groups[2],x=>x.label),['Insights','Analyze','CAISSA PGN Reader','Spectator TV','Lichess TV','Live Blitz','Live Tournaments','Lichess Broadcasts','Game Replayer','Arena']); const vercel=JSON.parse(read('vercel.json')); assert.ok(vercel.rewrites.some(x=>x.source==='/watch/lichess-broadcasts'&&x.destination==='/lichess-broadcasts.html')); assert.match(read('server.js'),/pathname === '\/watch\/lichess-broadcasts'/); assert.equal((read('public/sitemap.xml').match(/\/watch\/lichess-broadcasts<\/loc>/g)||[]).length,1); const inventory=JSON.parse(read('config/caissa-public-route-inventory.json')); assert.equal(inventory.primaryNavigation.filter(x=>x.id==='lichess-broadcasts').length,1); });
