import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {createMentorChatHandler} from '../api/mentor/chat.js';
const operationId=()=>crypto.randomUUID();const key=crypto.randomBytes(32).toString('base64');
function response(){return{statusCode:0,body:null,headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.body=v;return this;},end(){return this;}};}
function request(id){return{method:'POST',headers:{'idempotency-key':id},body:{provider:'together',messages:[{role:'user',content:'hello'}]}};}
function store(){const uid=crypto.randomUUID(),rid=crypto.randomUUID();let state='NEW',attempts=0,result=null;const calls=[];return{calls,internalUserId:uid,get attempts(){return attempts;},rpc:async(name,args)=>{calls.push(name);if(name==='claim_mentor_capacity')return{data:{allowed:true,lease_id:crypto.randomUUID(),remaining:5}};if(name==='release_mentor_capacity')return{data:true};if(name==='reserve_credits'){if(state==='CONSUMED')return{data:{success:true,code:'DUPLICATE',reservation_id:rid,user_id:uid,state:'CONSUMED',reserved_amount:1}};state='RESERVED';return{data:{success:true,reservation_id:rid,user_id:uid,state:'RESERVED',reserved_amount:1}};}if(name==='mark_reservation_provider_attempt'){if(attempts)return{data:{success:true,should_call_provider:false}};attempts++;return{data:{success:true,should_call_provider:true}};}if(name==='mark_mentor_result_available')return{data:true};if(name==='consume_reservation'){state='CONSUMED';return{data:{success:true}};}if(name==='release_reservation'){state='RELEASED';return{data:{success:true}};}if(name==='get_mentor_result_for_replay')return{data:result?{found:true,user_id:uid,schema_version:result.schema_version,ciphertext:result.ciphertext,iv:result.iv,auth_tag:result.auth_tag,delivered_at:null}:{found:false}};return{data:{success:true}};},from(name){if(name==='users')return{select(){return this;},eq(){return this;},async maybeSingle(){return{data:{id:uid},error:null};}};return{insert:async row=>{if(name==='mentor_operation_results')result=row;return{error:null};},delete(){return{eq(){return{eq:async()=>{result=null;return{error:null};}};}}}};}};}
const env={MENTOR_AI_ENABLED:'true',MENTOR_SHARED_AI_ENABLED:'true',TOGETHER_API_KEY:'server-key',TOGETHER_MODEL:'moonshotai/Kimi-K2.5',MENTOR_RATE_LIMIT_SECRET:'x'.repeat(32),CAISSA_MENTOR_RESERVATIONS_ENABLED:'true',CAISSA_MENTOR_RESULT_ENCRYPTION_KEY:key};
const auth=async()=>({authenticated:true,userId:'clerk_user'});const provider=async()=>({ok:true,json:async()=>({choices:[{message:{content:'answer'}}],usage:{prompt_tokens:2,completion_tokens:3}})});
const canaryEnv=db=>({...env,CAISSA_MENTOR_RESERVATION_CANARY_USER_IDS:db.internalUserId});
test('enabled allowlisted Shared Mentor persists then consumes and duplicate replays without provider call',async()=>{const db=store();let providerCalls=0;const handler=createMentorChatHandler({db,env:canaryEnv(db),authenticate:auth,fetchImpl:async(...args)=>{providerCalls++;return provider(...args);}});const id=operationId();const first=response();await handler(request(id),first);assert.equal(first.statusCode,200);assert.equal(providerCalls,1);assert.equal(db.calls.filter(x=>x==='consume_reservation').length,1);const second=response();await handler(request(id),second);assert.equal(second.statusCode,200);assert.equal(second.body.replayed,true);assert.equal(providerCalls,1);assert.equal(db.calls.filter(x=>x==='consume_reservation').length,1);});
test('missing encryption key fails before capacity and provider dispatch',async()=>{const db=store();let providerCalls=0;const handler=createMentorChatHandler({db,env:{...canaryEnv(db),CAISSA_MENTOR_RESULT_ENCRYPTION_KEY:undefined},authenticate:auth,fetchImpl:async()=>{providerCalls++;return provider();}});const res=response();await handler(request(operationId()),res);assert.equal(res.statusCode,503);assert.equal(providerCalls,0);assert.equal(db.calls.includes('claim_mentor_capacity'),false);});
test('provider rejection releases reservation and consumes zero',async()=>{const db=store();const handler=createMentorChatHandler({db,env:canaryEnv(db),authenticate:auth,fetchImpl:async()=>({ok:false,json:async()=>({})})});const res=response();await handler(request(operationId()),res);assert.equal(res.statusCode,502);assert.equal(db.calls.filter(x=>x==='release_reservation').length,1);assert.equal(db.calls.includes('consume_reservation'),false);});
test('provider timeout releases reservation and consumes zero',async()=>{const db=store();const handler=createMentorChatHandler({db,env:canaryEnv(db),authenticate:auth,fetchImpl:async()=>{throw Object.assign(new Error('synthetic'),{name:'AbortError'});}});const res=response();await handler(request(operationId()),res);assert.equal(res.statusCode,503);assert.equal(db.calls.filter(x=>x==='release_reservation').length,1);assert.equal(db.calls.includes('consume_reservation'),false);});
test('global ON without a valid allowlist fails before provider dispatch',async()=>{const db=store();let providerCalls=0;const handler=createMentorChatHandler({db,env,authenticate:auth,fetchImpl:async()=>{providerCalls++;return provider();}});const res=response();await handler(request(operationId()),res);assert.equal(res.statusCode,503);assert.equal(providerCalls,0);assert.equal(db.calls.includes('reserve_credits'),false);});
test('wrong internal user remains on legacy path with no reservation',async()=>{const db=store();const handler=createMentorChatHandler({db,env:{...env,CAISSA_MENTOR_RESERVATION_CANARY_USER_IDS:crypto.randomUUID()},authenticate:auth,fetchImpl:provider});const res=response();await handler(request(operationId()),res);assert.equal(res.statusCode,200);assert.equal(db.calls.includes('consume_credits'),true);assert.equal(db.calls.includes('reserve_credits'),false);});
test('BYO remains outside CAISSA reservation and credit RPCs',async()=>{const db=store();const handler=createMentorChatHandler({db,env,authenticate:auth,fetchImpl:provider});const req=request(operationId());req.body={provider:'openai',apiKey:'byo-secret',model:'gpt-4o-mini',messages:[{role:'user',content:'hello'}]};const res=response();await handler(req,res);assert.equal(res.statusCode,200);assert.equal(db.calls.includes('reserve_credits'),false);assert.equal(db.calls.includes('consume_credits'),false);});
