/** @type {import('../../../../schema/knowledge-unit.js').KnowledgeUnit} */
export const favorableKingEnding = {
    id: 'ku:endgames:pawn-exchanges:favorable-king-ending', slug: 'favorable-king-ending', domain: 'endgames', status: 'published', schemaVersion: '1.0.0', contentVersion: '1.0.0',
    education: { knowledgeType: 'decision-rule', endgameFamily: 'pawn-endgames', themes: ['favorable-simplification', 'exchange-decision', 'king-activity', 'opposition', 'key-squares'], skills: ['calculation', 'planning', 'move-order'], difficulty: 'intermediate', expectedLearnerLevel: 'foundation-rules-aware', prerequisites: ['ku:endgames:pawn-foundations:activate-the-king', 'ku:endgames:pawn-foundations:direct-opposition'],
        learningObjectives: ['Compare current and resulting pawn structures before simplifying.', 'Accept or reject simplification using king access, opposition, key squares, reserve tempi, and races.'],
        masteryCriteria: ['Names at least four changed features after simplification in four of five comparisons.', 'Selects the favorable transition or rejects a merely simpler ending in three of four tasks without a final hint.'] },
    localization: { defaultLocale: 'en-US', availableLocales: ['en-US'], translationStatus: { 'en-US': 'ready' }, content: { 'en-US': {
        title: 'Simplify into a favorable king ending', summary: 'Trade only when the resulting pawn ending improves concrete king access and structural prospects.',
        explanation: 'A simpler ending is favorable only when the resulting position preserves or increases the advantage. Every exchange can change king routes, opposition, key squares, reserve tempi, weaknesses, and races. Compare the current board with the reconstructed board after all captures. Do not trade merely because you are ahead; simplify when the resulting king ending gives a measurable access, structure, or race benefit.',
        keyIdeas: ['Simplification is an irreversible transition evaluated on the resulting board.', 'King activity and move order can outweigh the reduction in pawn count.'],
        misconceptions: ['Trading pawns when ahead is not a universal rule.', 'Fewer pawns do not guarantee easier conversion if the only target or reserve tempo disappears.'],
        practicalRules: ['Simplify when the resulting king access, target, or race is clearer and favorable.', 'Reject exchanges that improve only neatness while surrendering opposition or key squares.'],
        decisionProcess: ['Record the current structure and advantage.', 'List the full exchange sequence.', 'Reconstruct the resulting board.', 'Recalculate king routes, opposition, and key squares.', 'Check reserve tempi, weaknesses, and races.', 'Compare the measurable advantages before choosing.'],
        coachingPrompts: ['What concrete advantage exists before the exchange?', 'What type of king ending would remain?', 'Which exchange sequence must be reconstructed?', 'What changes in king access, opposition, targets, tempi, and races?', 'Use current board, full sequence, rebuilt board, and changed features.', 'Did simplification improve the position or only reduce material?'],
        reflectionPrompts: ['Which lost feature would make the transition unfavorable?', 'What measurable access or race benefit justifies simplifying?']
    } } },
    positions: [
        { id: 'pos:favorable-ending:open-king-route', fen: '8/8/5k2/3p4/2P1P3/3K4/8/8 w - - 0 1', sideToMove: 'white', role: 'clean-demonstration', expectedConcepts: ['favorable-simplification', 'king-route', 'resulting-structure'], principalIdeas: [{ moves: ['cxd5'], purpose: 'Clarify the center and evaluate the newly opened king route and remaining e-pawn.' }], validation: { structural: 'valid', educational: 'verified', notes: 'The legal capture and structural transition are verified; no tablebase result claimed.' } },
        { id: 'pos:favorable-ending:advantage-disappears', fen: '8/8/3k4/3p4/2P1P3/3K4/8/8 w - - 0 1', sideToMove: 'white', role: 'contrast', expectedConcepts: ['unfavorable-clarification', 'opposition-change', 'lost-target'], principalIdeas: [{ moves: ['cxd5'], purpose: 'Test a similar exchange with a differently placed defender and recalculate access.' }], validation: { structural: 'valid', educational: 'verified', notes: 'Changed king geometry makes this a distinct before-and-after comparison; no final-result claim.' } }
    ],
    learningObjects: { demonstrations: [{ id: 'demo:favorable-ending:before-after', positionId: 'pos:favorable-ending:open-king-route' }], guidedPractice: [{ id: 'guided:favorable-ending:feature-ledger', positionId: 'pos:favorable-ending:open-king-route', prompt: 'Record every changed feature before evaluating.' }], exercises: [{ id: 'exercise:favorable-ending:reject', positionId: 'pos:favorable-ending:advantage-disappears', task: 'Decide whether the exchange improves more than material simplicity.' }], checksForUnderstanding: [{ id: 'check:favorable-ending:criteria', prompt: 'Name four features that must be recalculated.' }], assessments: [{ id: 'assessment:favorable-ending:three-of-four', criterionId: 'favorable-transition-3-of-4' }], reviewItems: [{ id: 'review:pawn-exchanges:bounded-choice', conceptIds: ['pawn-tension', 'capture-order', 'divided-defense', 'favorable-simplification'] }] },
    relationships: [
        { type: 'remediation', targetId: 'ku:endgames:pawn-foundations:activate-the-king', reason: 'If simplification worsens king access, revisit purposeful king activation.' },
        { type: 'remediation', targetId: 'ku:endgames:pawn-foundations:direct-opposition', reason: 'If the exchange loses move-order access, revisit opposition and side to move.' },
        { type: 'remediation', targetId: 'ku:endgames:pawn-foundations:key-squares', reason: 'If the resulting king has no destination, revisit target-square evaluation.' },
        { type: 'related', targetId: 'ku:endgames:pawn-transformations:reserve-tempo', reason: 'Simplification can remove or create waiting moves that change the resulting king contest.' }
    ],
    integrations: { capabilities: ['academy-compatible', 'deterministic-coaching-prompts', 'mastery-criteria', 'training-memory-theme-link'], coaching: { policy: 'deterministic-prompt-only', conceptIds: ['favorable-simplification', 'before-after', 'king-access'], hintOrder: ['observation', 'structural-classification', 'candidate-identification', 'before-after-calculation', 'decision-process', 'reflection'] }, trainingMemory: { themeIds: ['favorable-simplification', 'exchange-decision', 'king-activity'] }, mastery: { criterionIds: ['simplification-features-4-of-5', 'favorable-transition-3-of-4'] }, recommendation: { remediationUnitIds: ['ku:endgames:pawn-foundations:activate-the-king', 'ku:endgames:pawn-foundations:direct-opposition', 'ku:endgames:pawn-foundations:key-squares'] }, academy: { compatible: true } },
    editorial: { owner: 'CAISSA Curriculum', reviewer: 'CAISSA Season 9 Review', createdAt: '2026-07-23', updatedAt: '2026-07-23', reviewStatus: 'approved', provenance: { kind: 'caissa-original', notes: 'Original CAISSA current-sequence-rebuild-feature-ledger decision rule.', inspirationReferences: [] }, copyrightNotes: 'No source prose or commercial sequence was copied.', originalityDeclaration: 'Independently authored for CAISSA.', verificationState: 'verified' }
};
