/** @type {import('../../../../schema/knowledge-unit.js').KnowledgeUnit} */
export const secondDistantTarget = {
    id: 'ku:endgames:pawn-exchanges:second-distant-target', slug: 'second-distant-target', domain: 'endgames', status: 'published', schemaVersion: '1.1.0', contentVersion: '1.1.0',
    education: { knowledgeType: 'principle', endgameFamily: 'pawn-endgames', themes: ['divided-defense', 'fixed-weakness', 'diversion', 'king-activity'], skills: ['planning', 'board-geometry', 'calculation'], difficulty: 'intermediate', expectedLearnerLevel: 'foundation-rules-aware', prerequisites: ['ku:endgames:pawn-transformations:outside-passed-pawn'],
        learningObjectives: ['Distinguish genuinely separated targets from two pawns covered by one king route.', 'Choose a king route that forces the defender to divide attention.'],
        masteryCriteria: ['Classifies a genuine second distant target in four of five structures.', 'Selects the correct approach and names the overloaded defensive route in three of four tasks.'] },
    localization: { defaultLocale: 'en-US', availableLocales: ['en-US'], translationStatus: { 'en-US': 'ready' }, content: { 'en-US': {
        title: 'Create a second distant target', summary: 'Stretch the defending king between separated pawn-ending responsibilities.',
        explanation: 'A second target matters when distance forces the defending king to choose between two responsibilities. Two weak pawns are not automatically two targets: one route or central square may cover both. In pawn endings, use a remote passer or fixed weakness to draw the king away, then approach the other wing. Calculate chase, return, and entry squares rather than invoking a universal two-weakness rule.',
        keyIdeas: ['Distance matters only when one defensive route cannot serve both targets in time.', 'The attacking king needs a concrete entry created by the defender’s diversion.'],
        misconceptions: ['Two weaknesses do not always win when one king route covers both.', 'Creating a remote pawn is pointless if no opposite-wing entry exists.'],
        practicalRules: ['Create targets on separated wings when the defender cannot shuttle between them.', 'Approach the target whose defense most restricts the enemy king.'],
        decisionProcess: ['Locate both candidate targets.', 'Measure their separation and defensive routes.', 'Test whether one route covers both.', 'Identify the diversion and opposite-wing entry.', 'Calculate chase and return.', 'Choose which target to approach first.'],
        coachingPrompts: ['Where are the two candidate targets?', 'Are they genuinely separated for the defending king?', 'Which target or passer can force a choice?', 'Can one route defend both, and what entry opens after diversion?', 'Use targets, routes, separation, diversion, and return time.', 'Which defensive responsibility became overloaded?'],
        reflectionPrompts: ['What central square would make the two targets false?', 'Which target should be approached first and why?']
    } } },
    positions: [
        { id: 'pos:second-target:separated-wings', fen: '8/8/4k3/8/P2K3P/8/8/8 w - - 0 1', sideToMove: 'white', role: 'clean-demonstration', expectedConcepts: ['second-distant-target', 'divided-defense', 'king-entry'], principalIdeas: [{ moves: ['Kc5'], purpose: 'Approach the queenside while preserving the distant kingside demand.' }], validation: { structural: 'valid', educational: 'verified', notes: 'Separated wings and legal approach verified without a forced-win claim.' } },
        { id: 'pos:second-target:single-route', fen: '8/8/3k4/8/2P1P3/3K4/8/8 w - - 0 1', sideToMove: 'white', role: 'contrast', expectedConcepts: ['false-second-target', 'shared-defense-route', 'central-king'], principalIdeas: [{ moves: ['Kd4'], purpose: 'Test the central route that continues to address both nearby pawns.' }], validation: { structural: 'valid', educational: 'verified', notes: 'Targets are close enough for a central defensive route; geometry is the lesson boundary.' } }
    ],
    learningObjects: { demonstrations: [{ id: 'demo:second-target:divide', positionId: 'pos:second-target:separated-wings' }], guidedPractice: [{ id: 'guided:second-target:routes', positionId: 'pos:second-target:separated-wings', prompt: 'Map both defensive routes and the attacking entry.' }], exercises: [{ id: 'exercise:second-target:false', positionId: 'pos:second-target:single-route', task: 'Explain why one route covers both targets.' }], checksForUnderstanding: [{ id: 'check:second-target:qualification', prompt: 'State what makes a second target genuine.' }], assessments: [{ id: 'assessment:second-target:three-of-four', criterionId: 'second-target-route-3-of-4' }], reviewItems: [] },
    activityItems: activityItemsFor('ku:endgames:pawn-exchanges:second-distant-target'),
    relationships: [
        { type: 'progression', targetId: 'ku:endgames:pawn-exchanges:favorable-king-ending', reason: 'After multiplying targets, learners decide whether an exchange preserves the divided defense in a simpler king ending.' },
        { type: 'related', targetId: 'ku:endgames:pawn-weaknesses:fix-pawn-weakness', reason: 'A fixed weakness can serve as one stable target while play develops on the other wing.' },
        { type: 'remediation', targetId: 'ku:endgames:pawn-transformations:outside-passed-pawn', reason: 'If the diversion route is miscalculated, revisit chase and return geometry.' }
    ],
    integrations: { capabilities: ['academy-compatible', 'deterministic-coaching-prompts', 'mastery-criteria', 'training-memory-theme-link'], coaching: { policy: 'deterministic-prompt-only', conceptIds: ['divided-defense', 'second-target', 'shared-route'], hintOrder: ['observation', 'structural-classification', 'candidate-identification', 'before-after-calculation', 'decision-process', 'reflection'] }, trainingMemory: { themeIds: ['divided-defense', 'diversion', 'fixed-weakness'] }, mastery: { criterionIds: ['second-target-classify-4-of-5', 'second-target-route-3-of-4'] }, recommendation: { nextUnitIds: ['ku:endgames:pawn-exchanges:favorable-king-ending'], remediationUnitIds: ['ku:endgames:pawn-transformations:outside-passed-pawn'] }, academy: { compatible: true } },
    editorial: { owner: 'CAISSA Curriculum', reviewer: 'CAISSA Season 9 Review', createdAt: '2026-07-23', updatedAt: '2026-07-25', reviewStatus: 'approved', provenance: { kind: 'caissa-original', notes: 'Original CAISSA targets-routes-separation-diversion sequence.', inspirationReferences: [] }, copyrightNotes: 'No source prose or commercial sequence was copied.', originalityDeclaration: 'Independently authored for CAISSA.', verificationState: 'verified' }
};
import { activityItemsFor } from '../../../../authoring/evaluable-endgame-activities.js';
