/** @type {import('../../../../schema/knowledge-unit.js').KnowledgeUnit} */
export const exchangeIntoPasser = {
    id: 'ku:endgames:pawn-exchanges:exchange-into-passer', slug: 'exchange-into-passer', domain: 'endgames', status: 'published', schemaVersion: '1.0.0', contentVersion: '1.0.0',
    education: { knowledgeType: 'technique', endgameFamily: 'pawn-endgames', themes: ['exchange-decision', 'capture-order', 'passed-pawns', 'pawn-races'], skills: ['calculation', 'move-order', 'board-geometry'], difficulty: 'intermediate', expectedLearnerLevel: 'foundation-rules-aware', prerequisites: ['ku:endgames:pawn-weaknesses:pawn-majority'],
        learningObjectives: ['Reconstruct the pawn structure after alternative capture orders.', 'Select an exchange that creates a viable passer without creating a faster enemy passer.'],
        masteryCriteria: ['Reconstructs the correct post-exchange structure in four of five sequences.', 'Selects capture order and verifies the race in three of four tasks without a final hint.'] },
    localization: { defaultLocale: 'en-US', availableLocales: ['en-US'], translationStatus: { 'en-US': 'ready' }, content: { 'en-US': {
        title: 'Exchange into a passed pawn', summary: 'Calculate capture direction and recapture order until the surviving passer and race are explicit.',
        explanation: 'Majority play develops a numerical advantage over time; exchange transformation asks what remains after a concrete capture sequence. Capture direction decides files, support, and whose passer survives. Record the structure, calculate forced recaptures, rebuild the board, and then apply king-distance checks. Creating a passer is useful only when the resulting race and king access work.',
        keyIdeas: ['Capture order determines the identity and route of the surviving pawn.', 'The exchange is unfinished analytically until the resulting king routes and race are checked.'],
        misconceptions: ['Any exchange that creates a passer is not automatically favorable.', 'Equivalent pawn counts can conceal different capture directions and races.'],
        practicalRules: ['Reconstruct the board after every forced recapture.', 'Reject an attractive passer when the exchange gives the opponent a faster one.'],
        decisionProcess: ['Record pawn counts and files.', 'List legal captures and advances.', 'Calculate recaptures.', 'Reconstruct the resulting structure.', 'Identify passers and candidates.', 'Recalculate king routes and reserve tempi.', 'Compare the final race.'],
        coachingPrompts: ['What are the current pawn counts and contacts?', 'Which resulting structures are possible?', 'Which capture order must be compared?', 'After all recaptures, which pawns and king routes remain?', 'Use count, captures, reconstruction, passers, routes, and race.', 'Did the exchange create a useful passer or a faster enemy threat?'],
        reflectionPrompts: ['Which capture direction changed the passer’s file?', 'What king-distance fact decides the final evaluation?']
    } } },
    positions: [
        { id: 'pos:exchange-passer:create', fen: '8/8/6k1/2p1p3/2PP4/5K2/8/8 w - - 0 1', sideToMove: 'white', role: 'clean-demonstration', expectedConcepts: ['capture-order', 'passed-pawn-creation', 'structure-reconstruction'], principalIdeas: [{ moves: ['dxe5'], purpose: 'Capture toward the open file and create a pawn with no opposing neighbor able to stop it.' }], validation: { structural: 'valid', educational: 'verified', notes: 'The legal capture and resulting passed-pawn status are structurally verified.' } },
        { id: 'pos:exchange-passer:enemy-race', fen: '8/8/6k1/2p1p3/2PP4/2K5/8/8 b - - 0 1', sideToMove: 'black', role: 'contrast', expectedConcepts: ['side-to-move', 'enemy-passer', 'race-check'], principalIdeas: [{ moves: ['exd4+'], purpose: 'Show that move order can give the opponent the transforming capture.' }], validation: { structural: 'valid', educational: 'verified', notes: 'The legal checking capture changes ownership of the initiative; no full-result claim is made.' } }
    ],
    learningObjects: { demonstrations: [{ id: 'demo:exchange-passer:rebuild', positionId: 'pos:exchange-passer:create' }], guidedPractice: [{ id: 'guided:exchange-passer:orders', positionId: 'pos:exchange-passer:create', prompt: 'Rebuild the board after each capture candidate.' }], exercises: [{ id: 'exercise:exchange-passer:enemy', positionId: 'pos:exchange-passer:enemy-race', task: 'Identify the opponent’s resulting passer and race.' }], checksForUnderstanding: [{ id: 'check:exchange-passer:complete', prompt: 'Name what must be checked after a passer appears.' }], assessments: [{ id: 'assessment:exchange-passer:three-of-four', criterionId: 'exchange-race-3-of-4' }], reviewItems: [] },
    relationships: [
        { type: 'progression', targetId: 'ku:endgames:pawn-exchanges:second-distant-target', reason: 'A created passer can become one of two separated demands on the defending king.' },
        { type: 'remediation', targetId: 'ku:endgames:pawn-foundations:rule-of-the-square', reason: 'Incorrect race evaluation requires exact pawn-square geometry.' },
        { type: 'contrast', targetId: 'ku:endgames:pawn-weaknesses:pawn-majority', reason: 'Majority play mobilizes over time; this unit resolves a concrete capture sequence.' },
        { type: 'related', targetId: 'ku:endgames:pawn-transformations:pawn-breakthrough', reason: 'Both transform structure, but exchange-to-passer need not sacrifice a pawn to deflect two defenders.' }
    ],
    integrations: { capabilities: ['academy-compatible', 'deterministic-coaching-prompts', 'mastery-criteria', 'training-memory-theme-link'], coaching: { policy: 'deterministic-prompt-only', conceptIds: ['capture-order', 'structure-reconstruction', 'passed-pawn'], hintOrder: ['observation', 'structural-classification', 'candidate-identification', 'before-after-calculation', 'decision-process', 'reflection'] }, trainingMemory: { themeIds: ['exchange-decision', 'capture-order', 'passed-pawns'] }, mastery: { criterionIds: ['exchange-rebuild-4-of-5', 'exchange-race-3-of-4'] }, recommendation: { nextUnitIds: ['ku:endgames:pawn-exchanges:second-distant-target'], remediationUnitIds: ['ku:endgames:pawn-foundations:rule-of-the-square'] }, academy: { compatible: true } },
    editorial: { owner: 'CAISSA Curriculum', reviewer: 'CAISSA Season 9 Review', createdAt: '2026-07-23', updatedAt: '2026-07-23', reviewStatus: 'approved', provenance: { kind: 'caissa-original', notes: 'Original CAISSA capture-rebuild-passer-route-race sequence.', inspirationReferences: [] }, copyrightNotes: 'No source prose or commercial sequence was copied.', originalityDeclaration: 'Independently authored for CAISSA.', verificationState: 'verified' }
};
