/** @type {import('../../../../schema/knowledge-unit.js').KnowledgeUnit} */
export const pawnTension = {
    id: 'ku:endgames:pawn-exchanges:pawn-tension', slug: 'pawn-tension', domain: 'endgames', status: 'published', schemaVersion: '1.0.0', contentVersion: '1.0.0',
    education: { knowledgeType: 'principle', endgameFamily: 'pawn-endgames', themes: ['pawn-tension', 'exchange-decision', 'pawn-structure', 'restraint'], skills: ['planning', 'calculation', 'move-order'], difficulty: 'developing', expectedLearnerLevel: 'foundation-rules-aware', prerequisites: [],
        learningObjectives: ['Recognize unresolved pawn contact and identify which side benefits from clarification.', 'Compare preserving tension with each legal capture or advance.'],
        masteryCriteria: ['Classifies useful versus passive tension in four of five structures.', 'Preserves or resolves tension correctly after comparing two candidates in three of four tasks.'] },
    localization: { defaultLocale: 'en-US', availableLocales: ['en-US'], translationStatus: { 'en-US': 'ready' }, content: { 'en-US': {
        title: 'Preserve useful pawn tension', summary: 'Keep unresolved pawn contact when clarification would improve the opponent’s structure or king route.',
        explanation: 'Pawn tension exists when opposing pawns can capture or change their contact. Preserving it keeps structural choices unresolved; resolving it changes files, targets, or access. This differs from a reserve tempo, which stores a waiting move to change move obligation. Tension is useful only while it restricts the opponent or preserves superior choices. If waiting concedes king access, clarification may be necessary.',
        keyIdeas: ['Tension preserves capture choices and structural uncertainty.', 'The right question is which structure remains after each clarification.'],
        misconceptions: ['Keeping tension is not automatically best when waiting loses access.', 'Tension is not a reserve tempo merely because a pawn has not moved.'],
        practicalRules: ['Often preserve tension when the opponent benefits from the only clean exchange.', 'Resolve it when waiting is passive or a concrete capture improves the resulting structure.'],
        decisionProcess: ['Record the current pawn contact.', 'List legal captures and advances.', 'Reconstruct each resulting structure.', 'Identify released routes and targets.', 'Compare waiting with clarification.', 'Choose the option that preserves the better structure.'],
        coachingPrompts: ['Which pawns are in unresolved contact?', 'Who benefits if the structure clarifies now?', 'Which capture, advance, or waiting candidate must be compared?', 'What exact structure and king route remain afterward?', 'Use contact, candidates, reconstruction, access, and comparison.', 'Did the choice preserve useful options or merely postpone a decision?'],
        reflectionPrompts: ['What opponent resource appears after the exchange?', 'What fact would make continued tension passive?']
    } } },
    positions: [
        { id: 'pos:pawn-tension:preserve-contact', fen: '8/8/3k4/4p3/3P4/2K5/8/8 w - - 0 1', sideToMove: 'white', role: 'clean-demonstration', expectedConcepts: ['pawn-tension', 'structural-options', 'king-route'], principalIdeas: [{ moves: ['Kc4'], purpose: 'Improve the king while leaving both pawn-capture choices unresolved.' }], validation: { structural: 'valid', educational: 'verified', notes: 'Legal contact and king move verified; no final result claimed.' } },
        { id: 'pos:pawn-tension:clarify-now', fen: '8/8/5k2/4p3/3P4/3K4/8/8 w - - 0 1', sideToMove: 'white', role: 'contrast', expectedConcepts: ['necessary-clarification', 'capture-choice', 'passive-waiting'], principalIdeas: [{ moves: ['dxe5+'], purpose: 'Resolve contact before the opposing king improves its approach.' }], validation: { structural: 'valid', educational: 'verified', notes: 'The checking capture is legal and illustrates a concrete reason to clarify.' } }
    ],
    learningObjects: { demonstrations: [{ id: 'demo:pawn-tension:options', positionId: 'pos:pawn-tension:preserve-contact' }], guidedPractice: [{ id: 'guided:pawn-tension:compare', positionId: 'pos:pawn-tension:preserve-contact', prompt: 'Compare waiting with clarification.' }], exercises: [{ id: 'exercise:pawn-tension:clarify', positionId: 'pos:pawn-tension:clarify-now', task: 'Explain why waiting is passive.' }], checksForUnderstanding: [{ id: 'check:pawn-tension:reserve-distinction', prompt: 'Distinguish structural tension from a waiting tempo.' }], assessments: [{ id: 'assessment:pawn-tension:three-of-four', criterionId: 'tension-choice-3-of-4' }], reviewItems: [] },
    relationships: [
        { type: 'contrast', targetId: 'ku:endgames:pawn-transformations:reserve-tempo', reason: 'Tension preserves unresolved captures; reserve tempo preserves a waiting move that transfers move obligation.' },
        { type: 'progression', targetId: 'ku:endgames:pawn-exchanges:exchange-into-passer', reason: 'After comparing whether to clarify, learners calculate a capture sequence that deliberately creates a passer.' },
        { type: 'related', targetId: 'ku:endgames:pawn-weaknesses:fix-pawn-weakness', reason: 'Clarification can release a fixed weakness that tension was helping restrain.' }
    ],
    integrations: { capabilities: ['academy-compatible', 'deterministic-coaching-prompts', 'mastery-criteria', 'training-memory-theme-link'], coaching: { policy: 'deterministic-prompt-only', conceptIds: ['pawn-tension', 'clarification'], hintOrder: ['observation', 'structural-classification', 'candidate-identification', 'before-after-calculation', 'decision-process', 'reflection'] }, trainingMemory: { themeIds: ['pawn-tension', 'exchange-decision'] }, mastery: { criterionIds: ['tension-classify-4-of-5', 'tension-choice-3-of-4'] }, recommendation: { nextUnitIds: ['ku:endgames:pawn-exchanges:exchange-into-passer'] }, academy: { compatible: true } },
    editorial: { owner: 'CAISSA Curriculum', reviewer: 'CAISSA Season 9 Review', createdAt: '2026-07-23', updatedAt: '2026-07-23', reviewStatus: 'approved', provenance: { kind: 'caissa-original', notes: 'Original CAISSA contact-candidates-reconstruction-access sequence.', inspirationReferences: [] }, copyrightNotes: 'No source prose or commercial sequence was copied.', originalityDeclaration: 'Independently authored for CAISSA.', verificationState: 'verified' }
};
