import test from 'node:test';
import assert from 'node:assert/strict';
import { createTrainingMemory, normalizeTrainingMemory, recordTrainingSession, summarizeTrainingMemory, exportTrainingMemory, importTrainingMemory } from '../../js/endgame-trainer/endgame-training-memory.js';
import { createEndgameProgressStore } from '../../js/endgame-trainer/endgame-progress-store.js';

const session = (patch = {}) => ({ id: 'session-1', lessonId: 'pawn-opposition', theme: 'opposition', outcome: 'solved', hintsUsed: 0, attempts: 1, durationMs: 60000, finalResult: 'checkmate', classifications: { BEST: 2, GOOD: 1, SUCCESS: 1 }, timestamp: 1000, ...patch });
const storage = (initial = null) => { let value = initial; return { getItem: () => value, setItem: (_key, next) => { value = next; }, raw: () => value }; };

test('fresh memory is versioned and empty', () => assert.deepEqual(createTrainingMemory(), { version: 1, sessions: [] }));
test('record stores a sanitized session once', () => { const first = recordTrainingSession(createTrainingMemory(), session()); assert.equal(first.recorded, true); assert.equal(recordTrainingSession(first.memory, session()).recorded, false); });
test('history is newest first with deterministic tie ordering', () => { let state = recordTrainingSession(createTrainingMemory(), session({ id: 'b', timestamp: 1 })).memory; state = recordTrainingSession(state, session({ id: 'a', timestamp: 2 })).memory; assert.deepEqual(state.sessions.map(item => item.id), ['a', 'b']); });
test('legacy memory v0 migrates automatically', () => assert.equal(normalizeTrainingMemory({ version: 0, history: [session()] }).sessions.length, 1));
test('corrupted fields recover to safe defaults', () => { const value = normalizeTrainingMemory({ version: 1, sessions: [{ ...session(), hintsUsed: -2, classifications: { BEST: -1 } }] }); assert.equal(value.sessions[0].hintsUsed, 0); assert.equal(value.sessions[0].classifications.BEST, 0); });
test('statistics aggregate themes and move classifications', () => { let state = recordTrainingSession(createTrainingMemory(), session()).memory; state = recordTrainingSession(state, session({ id: 'session-2', outcome: 'failed', classifications: { MISTAKE: 2 }, timestamp: 2000 })).memory; const summary = summarizeTrainingMemory(state); assert.equal(summary.themes.opposition.attempts, 2); assert.equal(summary.moves.MISTAKE, 2); assert.equal(summary.overall.accuracy, 50); });
test('mastery evolves deterministically', () => { let state = createTrainingMemory(); for (let index = 0; index < 6; index += 1) state = recordTrainingSession(state, session({ id: `success-${index}`, timestamp: index, classifications: { BEST: 3, SUCCESS: 1 } })).memory; const mastery = summarizeTrainingMemory(state).themes.opposition.mastery; assert.equal(mastery.level, 'Mastered'); assert.equal(mastery.score, 95); });
test('weakness and recommendation are computed from measurements', () => { let state = recordTrainingSession(createTrainingMemory(), session()).memory; state = recordTrainingSession(state, session({ id: 'weak', lessonId: 'rook-philidor', theme: 'philidor-like', outcome: 'failed', hintsUsed: 4, classifications: { BLUNDER: 2 }, timestamp: 2000 })).memory; const summary = summarizeTrainingMemory(state); assert.equal(summary.weakness.mostDifficultTheme, 'philidor-like'); assert.equal(summary.recommendation.type, 'retry-mistake'); });
test('export and import round trip exactly', () => { const memory = recordTrainingSession(createTrainingMemory(), session()).memory, result = importTrainingMemory(exportTrainingMemory(memory)); assert.equal(result.ok, true); assert.deepEqual(result.memory, memory); });
test('malformed and invalid imports are rejected safely', () => { assert.deepEqual(importTrainingMemory('{bad'), { ok: false, error: 'invalid-json' }); assert.deepEqual(importTrainingMemory('{}'), { ok: false, error: 'invalid-training-memory' }); });
test('store persists memory across reload and supports reset', () => { const adapter = storage(), first = createEndgameProgressStore({ storage: adapter, now: () => 1000 }); first.load(); first.recordTrainingSession(session()); const second = createEndgameProgressStore({ storage: adapter }); second.load(); assert.equal(second.getTrainingSummary().overall.attempts, 1); second.reset(); assert.equal(second.getTrainingSummary().overall.attempts, 0); });
test('store import is transactional on invalid JSON', () => { const adapter = storage(), store = createEndgameProgressStore({ storage: adapter }); store.load(); store.recordTrainingSession(session()); assert.equal(store.importTrainingMemory('{bad').ok, false); assert.equal(store.getTrainingSummary().overall.attempts, 1); });
test('same sessions always produce byte-identical summaries', () => { const memory = recordTrainingSession(createTrainingMemory(), session()).memory; assert.equal(JSON.stringify(summarizeTrainingMemory(memory)), JSON.stringify(summarizeTrainingMemory(memory))); });
