import test from 'node:test';
import assert from 'node:assert/strict';
import { mountEndgameTrainerPage, unmountEndgameTrainerPage, getEndgameTrainerPageState } from '../../js/endgame-trainer/endgame-trainer-page.js';

class Classes { constructor() { this.values = new Set(); } toggle(v, on) { on === undefined ? (this.values.has(v) ? this.values.delete(v) : this.values.add(v)) : on ? this.values.add(v) : this.values.delete(v); } remove(v) { this.values.delete(v); } contains(v) { return this.values.has(v); } }
class Element extends EventTarget { constructor(key = '') { super(); this.dataset = key ? { navKey: key } : {}; this.classList = new Classes(); this.attrs = {}; this.value = key; this.textContent = ''; this.focused = 0; this.disabled = false; } setAttribute(k, v) { this.attrs[k] = String(v); } removeAttribute(k) { delete this.attrs[k]; } focus() { this.focused++; } contains(target) { return target === this; } querySelector() { return this.link; } }
function fixture(search = '') {
    const toggle = new Element(), nav = new Element(), state = new Element(), preview = new Element(), cta = new Element(); nav.link = new Element();
    const items = ['play', 'endgame-trainer', 'academy'].map(k => new Element(k)); const controls = [new Element('White')]; const actions = ['prepare', 'start', 'hint', 'undo', 'restart', 'new', 'resign', 'flip'].map(k => { const item = new Element(); item.dataset.action = k; return item; });
    const root = { dataset: {}, classList: new Classes(), querySelector(s) { return ({ '[data-mobile-nav]': nav, '[data-mobile-nav-toggle]': toggle, '[data-diagnostic-state]': state, '[data-preview-message]': preview, '[data-preview-cta]': cta })[s] ?? null; }, querySelectorAll(s) { return s === '[data-nav-key]' ? items : s === '[data-preview-option]' ? controls : s === '[data-action]' ? actions : []; } };
    const doc = new EventTarget(); doc.querySelector = () => root; const win = new EventTarget(); win.location = { search }; win.innerWidth = 390;
    return { root, doc, win, toggle, nav, state, preview, cta, items, controls, actions };
}
function drawerControllerFactory({ host, toggle, document, window, onStateChange }) {
    let open = false;
    const apply = (next, focus = false) => { open = next; host.classList.toggle('is-nav-open', open); toggle.setAttribute('aria-expanded', String(open)); onStateChange?.(open); if (focus) toggle.focus(); };
    const click = () => apply(!open); const key = event => { if (event.key === 'Escape' && open) apply(false, true); }; const outside = event => { if (open && event.target !== toggle) apply(false); }; const resize = () => { if (open && window.innerWidth > 768) apply(false); };
    toggle.addEventListener('click', click); document.addEventListener('keydown', key); document.addEventListener('click', outside); window.addEventListener('resize', resize);
    apply(false);
    return { open: () => apply(true), close: ({ returnFocus = false } = {}) => apply(false, returnFocus), destroy() { toggle.removeEventListener('click', click); document.removeEventListener('keydown', key); document.removeEventListener('click', outside); window.removeEventListener('resize', resize); } };
}
function mount(search = '') { unmountEndgameTrainerPage(); const f = fixture(search); mountEndgameTrainerPage({ root: f.root, document: f.doc, window: f.win, drawerControllerFactory }); return f; }
const click = el => el.dispatchEvent(new Event('click'));
const escape = doc => { const event = new Event('keydown'); Object.defineProperty(event, 'key', { value: 'Escape' }); doc.dispatchEvent(event); };

test('1 invalid root', () => assert.throws(() => mountEndgameTrainerPage({ root: {}, document: {}, window: {} }), /invalid-root/));
test('2 mount success', () => { mount(); assert.equal(getEndgameTrainerPageState().mounted, true); });
test('3 mount twice', () => { const f = mount(); assert.deepEqual(mountEndgameTrainerPage({ root: f.root, document: f.doc, window: f.win }), getEndgameTrainerPageState()); });
test('4 active nav item', () => { const f = mount(); assert.ok(f.items[1].classList.contains('is-active')); });
test('5 only one aria-current', () => { const f = mount(); assert.equal(f.items.filter(x => x.attrs['aria-current'] === 'page').length, 1); });
for (const [n, state] of [[6, 'empty'], [7, 'loading'], [8, 'error'], [9, 'completed']]) test(`${n} diagnostic ${state}`, () => { const f = mount(`?diagnostic=1&diagnosticState=${state}`); assert.equal(f.root.dataset.state, state); });
test('10 invalid diagnostic state fallback', () => { const f = mount('?state=bad'); assert.equal(f.root.dataset.state, 'empty'); });
test('11 mobile nav open', () => { const f = mount(); click(f.toggle); assert.equal(getEndgameTrainerPageState().navOpen, true); });
test('12 mobile nav close', () => { const f = mount(); click(f.toggle); click(f.toggle); assert.equal(getEndgameTrainerPageState().navOpen, false); });
test('13 Escape close', () => { const f = mount(); click(f.toggle); escape(f.doc); assert.equal(getEndgameTrainerPageState().navOpen, false); });
test('14 click outside close', () => { const f = mount(); click(f.toggle); f.doc.dispatchEvent(new Event('click')); assert.equal(getEndgameTrainerPageState().navOpen, false); });
test('15 aria-expanded', () => { const f = mount(); click(f.toggle); assert.equal(f.toggle.attrs['aria-expanded'], 'true'); });
test('16 focus return', () => { const f = mount(); click(f.toggle); escape(f.doc); assert.equal(f.toggle.focused, 1); });
test('17 shell fake does not create runtime without board', () => { mount(); assert.equal(getEndgameTrainerPageState().runtimeAttached, false); });
test('18 page state separates operation and controller', () => { mount(); const s = getEndgameTrainerPageState(); assert.equal(s.operation, null); assert.equal(s.controllerState.status, 'idle'); });
test('19 controls disabled contract is static markup concern', () => { const f = mount(); assert.equal(f.controls.length, 1); });
test('20 unmount', () => { mount(); assert.equal(unmountEndgameTrainerPage(), true); });
test('21 unmount idempotent', () => { mount(); unmountEndgameTrainerPage(); assert.equal(unmountEndgameTrainerPage(), false); });
test('22 remount no duplicate listeners', () => { const f = mount(); unmountEndgameTrainerPage(); mountEndgameTrainerPage({ root: f.root, document: f.doc, window: f.win, drawerControllerFactory }); click(f.toggle); assert.equal(getEndgameTrainerPageState().navOpen, true); });
test('23 snapshot immutable', () => { mount(); const s = getEndgameTrainerPageState(); s.mounted = false; assert.equal(getEndgameTrainerPageState().mounted, true); });
test('24 approved runtime import only', async () => { const source = await import('node:fs/promises').then(fs => fs.readFile(new URL('../../js/endgame-trainer/endgame-trainer-page.js', import.meta.url), 'utf8')); assert.match(source, /createEndgameTrainerRuntime/); assert.doesNotMatch(source, /app\.js|CaissaNavigation|localStorage|sessionStorage/); });
test('25 root-scoped product queries', async () => { const source = await import('node:fs/promises').then(fs => fs.readFile(new URL('../../js/endgame-trainer/endgame-trainer-page.js', import.meta.url), 'utf8')); assert.equal((source.match(/doc\?\.querySelector/g) ?? []).length, 1); });
test('26 metadata and canonical contract', async () => { const html = await import('node:fs/promises').then(fs => fs.readFile(new URL('../../endgame-trainer.html', import.meta.url), 'utf8')); assert.match(html, /<link rel="canonical" href="https:\/\/www\.caissa-chess\.org\/endgame-trainer">/); assert.equal((html.match(/<title>/g) ?? []).length, 1); });
test('28 complete standalone links', async () => { const html = await import('node:fs/promises').then(fs => fs.readFile(new URL('../../endgame-trainer.html', import.meta.url), 'utf8')); for (const label of ['Playchess','Fritz','Tactics','Insights','Spectator TV','Lichess TV','Live Blitz','Cheater Insight','Polyglot Tool','Opening Database','ECO Codes','Game Library','History','DOS Chess','Vault','Blog','CAISSA Chess YouTube','Share an Idea / Contact & Feedback']) assert.match(html, new RegExp(`>${label}<`)); });
test('28 assets are root-relative', async () => { const html = await import('node:fs/promises').then(fs => fs.readFile(new URL('../../endgame-trainer.html', import.meta.url), 'utf8')); assert.match(html, /href="\/css\/endgame-trainer\.css"/); assert.match(html, /src="\/js\/endgame-trainer\/endgame-trainer-page\.js"/); });
test('29 auth uses real sign-in destination', async () => { const html = await import('node:fs/promises').then(fs => fs.readFile(new URL('../../endgame-trainer.html', import.meta.url), 'utf8')); assert.match(html, /class="[^"]*endgame-trainer-page__auth[^"]*" href="\/signin"/); });
test('30 resize to desktop closes mobile nav', () => { const f = mount(); click(f.toggle); f.win.innerWidth = 1024; f.win.dispatchEvent(new Event('resize')); assert.equal(getEndgameTrainerPageState().navOpen, false); });
test('31 unmount disables every static product action', () => { const f = mount(); unmountEndgameTrainerPage(); assert.equal(f.actions.every(action => action.disabled), true); });
const blankProgress = () => ({ version: 1, totals: { positionsPrepared: 0, sessionsStarted: 0, sessionsCompleted: 0, checkmates: 0, stalemates: 0, draws: 0, resignations: 0, abandoned: 0, hintsUsed: 0, undosUsed: 0, attempts: 0 }, categories: Object.fromEntries(['KQK','KRK','KPK','KPKP'].map(id => [id, { sessionsStarted: 0, sessionsCompleted: 0, checkmates: 0 }])), recentSessions: [], completionRate: 0, persistence: { available: true, errorCode: null } });
function fakeStore() { return { loads: 0, refreshes: 0, disposes: 0, snapshot: blankProgress(), load() { this.loads++; }, refreshFromStorage() { this.refreshes++; return structuredClone(this.snapshot); }, isStorageArea: value => !value || value?.kind === 'local', getSnapshot() { return structuredClone(this.snapshot); }, getDiagnosticSnapshot: () => ({}), recordPreparedPosition() {}, recordSessionStarted() {}, recordSessionCompleted() {}, recordSessionResigned() {}, recordSessionAbandoned() {}, reset() {}, dispose() { this.disposes++; } }; }
test('32 progress store created once per mount', () => { unmountEndgameTrainerPage(); const f = fixture(), store = fakeStore(); let created = 0; mountEndgameTrainerPage({ root: f.root, document: f.doc, window: f.win, progressStoreFactory: () => { created++; return store; } }); mountEndgameTrainerPage({ root: f.root, document: f.doc, window: f.win, progressStoreFactory: () => store }); assert.equal(created, 1); assert.equal(store.loads, 1); });
test('33 progress store disposed on unmount', () => { unmountEndgameTrainerPage(); const f = fixture(), store = fakeStore(); mountEndgameTrainerPage({ root: f.root, document: f.doc, window: f.win, progressStoreFactory: () => store }); unmountEndgameTrainerPage(); assert.equal(store.disposes, 1); });
test('34 diagnostic progress snapshot is gated', () => { unmountEndgameTrainerPage(); const f = fixture('?diagnostic=1'), store = fakeStore(); store.getDiagnosticSnapshot = () => ({ schemaVersion: 1 }); mountEndgameTrainerPage({ root: f.root, document: f.doc, window: f.win, progressStoreFactory: () => store }); assert.equal(getEndgameTrainerPageState().progressDiagnostic.schemaVersion, 1); });
test('35 normal mode omits progress diagnostics', () => { const f = mount(); assert.equal(getEndgameTrainerPageState().progressDiagnostic, undefined); });
const storageEvent = (key, newValue = '{}', storageArea = null) => { const event = new Event('storage'); Object.defineProperties(event, { key: { value: key }, newValue: { value: newValue }, storageArea: { value: storageArea } }); return event; };
test('36 matching storage event refreshes once', () => { unmountEndgameTrainerPage(); const f = fixture(), store = fakeStore(); store.snapshot.totals.sessionsStarted = 2; mountEndgameTrainerPage({ root: f.root, document: f.doc, window: f.win, progressStoreFactory: () => store }); f.win.dispatchEvent(storageEvent('caissa:endgame-trainer:progress:v1')); assert.equal(store.refreshes, 1); assert.equal(getEndgameTrainerPageState().progress.totals.sessionsStarted, 2); });
test('37 unrelated storage key ignored', () => { unmountEndgameTrainerPage(); const f = fixture(), store = fakeStore(); mountEndgameTrainerPage({ root: f.root, document: f.doc, window: f.win, progressStoreFactory: () => store }); f.win.dispatchEvent(storageEvent('other')); assert.equal(store.refreshes, 0); });
test('38 different storage area ignored', () => { unmountEndgameTrainerPage(); const f = fixture(), store = fakeStore(); mountEndgameTrainerPage({ root: f.root, document: f.doc, window: f.win, progressStoreFactory: () => store }); f.win.dispatchEvent(storageEvent('caissa:endgame-trainer:progress:v1', '{}', {})); assert.equal(store.refreshes, 0); });
test('39 external update feedback', () => { unmountEndgameTrainerPage(); const f = fixture(), store = fakeStore(); store.snapshot.totals.sessionsStarted = 1; mountEndgameTrainerPage({ root: f.root, document: f.doc, window: f.win, progressStoreFactory: () => store }); f.win.dispatchEvent(storageEvent('caissa:endgame-trainer:progress:v1')); assert.equal(getEndgameTrainerPageState().syncFeedback, 'Training progress updated from another tab.'); });
test('40 external reset feedback', () => { unmountEndgameTrainerPage(); const f = fixture(), store = fakeStore(); mountEndgameTrainerPage({ root: f.root, document: f.doc, window: f.win, progressStoreFactory: () => store }); f.win.dispatchEvent(storageEvent('caissa:endgame-trainer:progress:v1', null)); assert.equal(getEndgameTrainerPageState().syncFeedback, 'Training progress was reset in another tab.'); });
test('41 event after unmount ignored', () => { unmountEndgameTrainerPage(); const f = fixture(), store = fakeStore(); mountEndgameTrainerPage({ root: f.root, document: f.doc, window: f.win, progressStoreFactory: () => store }); unmountEndgameTrainerPage(); f.win.dispatchEvent(storageEvent('caissa:endgame-trainer:progress:v1')); assert.equal(store.refreshes, 0); });
test('42 remount has one effective storage listener', () => { unmountEndgameTrainerPage(); const f = fixture(), first = fakeStore(), second = fakeStore(); mountEndgameTrainerPage({ root: f.root, document: f.doc, window: f.win, progressStoreFactory: () => first }); unmountEndgameTrainerPage(); mountEndgameTrainerPage({ root: f.root, document: f.doc, window: f.win, progressStoreFactory: () => second }); f.win.dispatchEvent(storageEvent('caissa:endgame-trainer:progress:v1')); assert.equal(first.refreshes, 0); assert.equal(second.refreshes, 1); });
test('43 recent UI state resets on remount', () => { const f = mount(); const state = getEndgameTrainerPageState(); assert.equal(state.recentExpanded, false); assert.equal(state.recentResult, 'all'); assert.equal(state.recentCategory, 'all'); });
