import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createEndgameProgressStore, ENDGAME_PROGRESS_STORAGE_KEY } from '../../js/endgame-trainer/endgame-progress-store.js';

const memory = (initial = null) => { let value = initial; return { getItem: () => value, setItem: (_key, next) => { value = next; }, removeItem: () => { value = null; }, raw: () => value }; };
const make = (initial, options = {}) => { const storage = Object.hasOwn(options, 'storage') ? options.storage : memory(initial), store = createEndgameProgressStore({ storage, now: options.now ?? (() => 1000) }); store.load(); return { store, storage }; };
const entry = (overrides = {}) => ({ id: 's1', category: 'KQK', pieceCount: 3, userColor: 'white', result: 'checkmate', attemptNumber: 2, hintsUsed: 1, undosUsed: 1, moveCount: 7, preparedAt: 100, endedAt: 1000, durationMs: 900, initialFen: 'fen-a', finalFen: 'fen-b', ...overrides });

test('1 fresh state', () => assert.equal(make(null).store.getSnapshot().totals.sessionsStarted, 0));
test('2 valid load', () => { const data = make(null).store.getSnapshot(); data.totals.sessionsStarted = 3; const { store } = make(JSON.stringify(data)); assert.equal(store.getSnapshot().totals.sessionsStarted, 3); });
test('3 malformed JSON', () => assert.equal(make('{bad').store.getSnapshot().persistence.errorCode, 'invalid-json'));
test('4 null payload', () => assert.equal(make('null').store.getSnapshot().totals.positionsPrepared, 0));
test('5 primitive payload', () => assert.equal(make('4').store.getSnapshot().totals.positionsPrepared, 0));
test('6 missing version', () => assert.equal(make('{}').store.getSnapshot().version, 1));
test('7 known v0 migration', () => assert.equal(make(JSON.stringify({ version: 0, totals: { sessionsStarted: 2 } })).store.getSnapshot().totals.sessionsStarted, 2));
test('8 unknown future version uses fresh memory without overwrite', () => { const storage = memory(JSON.stringify({ version: 9 })); const { store } = make(null, { storage }); store.recordPreparedPosition(entry()); assert.match(storage.raw(), /"version":9/); });
test('9 negative values sanitize', () => assert.equal(make(JSON.stringify({ version: 1, totals: { attempts: -3 } })).store.getSnapshot().totals.attempts, 0));
test('10 invalid numeric values sanitize', () => assert.equal(make(JSON.stringify({ version: 1, totals: { attempts: 'NaN' } })).store.getSnapshot().totals.attempts, 0));
test('11 category validation', () => assert.equal(Object.keys(make(null).store.getSnapshot().categories).length, 4));
test('12 unknown category ignored', () => assert.equal(make(JSON.stringify({ version: 1, categories: { OTHER: { sessionsStarted: 8 } } })).store.getSnapshot().categories.OTHER, undefined));
test('13 recent sessions capped at 20', () => { const recentSessions = Array.from({ length: 25 }, (_, i) => entry({ id: `s${i}` })); assert.equal(make(JSON.stringify({ version: 1, recentSessions })).store.getSnapshot().recentSessions.length, 20); });
test('14 record prepared once', () => { const { store } = make(null); assert.equal(store.recordPreparedPosition(entry()), true); assert.equal(store.recordPreparedPosition(entry()), false); assert.equal(store.getSnapshot().totals.positionsPrepared, 1); });
test('15 record started once', () => { const { store } = make(null); store.recordSessionStarted(entry()); store.recordSessionStarted(entry()); assert.equal(store.getSnapshot().totals.sessionsStarted, 1); });
test('16 record completed once', () => { const { store } = make(null); store.recordSessionCompleted(entry()); store.recordSessionCompleted(entry()); assert.equal(store.getSnapshot().totals.sessionsCompleted, 1); });
test('17 record checkmate', () => { const { store } = make(null); store.recordSessionCompleted(entry()); assert.equal(store.getSnapshot().totals.checkmates, 1); });
test('18 record stalemate', () => { const { store } = make(null); store.recordSessionCompleted(entry({ result: 'stalemate' })); assert.equal(store.getSnapshot().totals.stalemates, 1); });
test('19 record draw', () => { const { store } = make(null); store.recordSessionCompleted(entry({ result: 'draw' })); assert.equal(store.getSnapshot().totals.draws, 1); });
test('20 record resigned', () => { const { store } = make(null); store.recordSessionResigned(entry()); assert.equal(store.getSnapshot().totals.resignations, 1); });
test('21 record abandoned', () => { const { store } = make(null); store.recordSessionAbandoned(entry()); assert.equal(store.getSnapshot().totals.abandoned, 1); });
test('22 hints aggregated at terminal', () => { const { store } = make(null); store.recordSessionCompleted(entry({ hintsUsed: 4 })); assert.equal(store.getSnapshot().totals.hintsUsed, 4); });
test('23 undos aggregated at terminal', () => { const { store } = make(null); store.recordSessionCompleted(entry({ undosUsed: 3 })); assert.equal(store.getSnapshot().totals.undosUsed, 3); });
test('24 attempts aggregated at terminal', () => { const { store } = make(null); store.recordSessionCompleted(entry({ attemptNumber: 5 })); assert.equal(store.getSnapshot().totals.attempts, 5); });
test('25 completion rate zero safe and calculated', () => { const { store } = make(null); assert.equal(store.getSnapshot().completionRate, 0); store.recordSessionStarted(entry()); store.recordSessionCompleted(entry()); assert.equal(store.getSnapshot().completionRate, 100); });
test('26 category aggregation', () => { const { store } = make(null); store.recordSessionStarted(entry({ category: 'KRK' })); assert.equal(store.getSnapshot().categories.KRK.sessionsStarted, 1); });
test('27 defensive snapshot', () => { const { store } = make(null); const snap = store.getSnapshot(); snap.totals.sessionsStarted = 99; assert.equal(store.getSnapshot().totals.sessionsStarted, 0); });
test('28 storage unavailable', () => assert.equal(make(null, { storage: null }).store.getSnapshot().persistence.available, false));
test('29 quota error is nonfatal', () => { const storage = { getItem: () => null, setItem: () => { const e = new Error(); e.name = 'QuotaExceededError'; throw e; } }; const { store } = make(null, { storage }); assert.doesNotThrow(() => store.recordPreparedPosition(entry())); assert.equal(store.getSnapshot().persistence.errorCode, 'quota-exceeded'); });
test('30 reset', () => { const { store } = make(null); store.recordSessionStarted(entry()); store.reset(); assert.equal(store.getSnapshot().totals.sessionsStarted, 0); });
test('31 dispose idempotent', () => { const { store } = make(null); assert.equal(store.dispose(), true); assert.equal(store.dispose(), false); });
test('32 write after dispose rejected', () => { const { store } = make(null); store.dispose(); assert.throws(() => store.recordPreparedPosition(entry()), /disposed/); });
test('33 storage key exact', () => assert.equal(ENDGAME_PROGRESS_STORAGE_KEY, 'caissa:endgame-trainer:progress:v1'));
test('34 no network or DOM dependency', async () => { const source = await readFile(new URL('../../js/endgame-trainer/endgame-progress-store.js', import.meta.url), 'utf8'); assert.doesNotMatch(source, /fetch|XMLHttpRequest|sendBeacon|WebSocket|document|window|cookie|sessionStorage|indexedDB/i); });
test('35 no runtime imports', async () => { const source = await readFile(new URL('../../js/endgame-trainer/endgame-progress-store.js', import.meta.url), 'utf8'); assert.doesNotMatch(source, /runtime|controller|binding|worker|chessboard/i); });
test('36 recent terminal deduplicates across remount', () => { const storage = memory(); make(null, { storage }).store.recordSessionCompleted(entry()); const second = make(null, { storage }).store; assert.equal(second.recordSessionCompleted(entry()), false); assert.equal(second.getSnapshot().totals.sessionsCompleted, 1); });
