import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { MultiMovePilotController, shouldActivateMultiMovePilot } from '../../js/endgame-trainer/v2/multi-move-pilot.js';
const artifact=JSON.parse(await readFile(new URL('../../public/data/endgame-pilots/kp-coordinate-support-promote/1.0.0.json',import.meta.url)));
const intent=uci=>({from:uci.slice(0,2),to:uci.slice(2,4),...(uci[4]?{promotion:uci[4]}:{})});
async function run(moves){const c=new MultiMovePilotController({artifact});await c.start();for(const move of moves)assert.equal(await c.submitMove(intent(move)),true);return c;}
test('strict pilot flag preserves Guided precedence',()=>{assert.equal(shouldActivateMultiMovePilot('?trainerV2=1&multiMovePilot=1'),true);assert.equal(shouldActivateMultiMovePilot('?trainerV2=1&multiMovePilot=true'),false);assert.equal(shouldActivateMultiMovePilot('?trainerV2=1&multiMovePilot=1&studyUnit=x'),false);});
test('both branches reach deterministic queen promotion',async()=>{const a=await run(['e5e6','e4e5','e6d5','e5e6','e6e7','e7e8q']);const b=await run(['e5f6','e4e5','e5e6','e6e7','e7e8q']);assert.equal(a.getState().result,'independent-success');assert.equal(b.getState().result,'independent-success');assert.equal(a.getState().ply,11);assert.equal(b.getState().ply,9);});
test('concept miss restores node and bounded losing deviation fails',async()=>{const a=new MultiMovePilotController({artifact});await a.start();assert.equal(await a.submitMove(intent('e5f5')),false);assert.equal(a.getState().fen,artifact.initialFen);assert.match(a.getState().feedback,/may preserve/);const b=new MultiMovePilotController({artifact});await b.start();assert.equal(await b.submitMove(intent('e5d5')),true);assert.equal(b.getState().phase,'objective-failure');});
test('hints, retry, abandon, duplicate and stale callbacks are guarded',async()=>{let release;const c=new MultiMovePilotController({artifact,delay:()=>new Promise(r=>{release=r})});await c.start();c.hint();c.hint();c.hint();assert.equal(c.getState().independentEligible,false);const pending=c.submitMove(intent('e5e6'));assert.equal(await c.submitMove(intent('e5e6')),false);c.abandon();release();await pending;assert.equal(c.getState().phase,'item-abandoned');const f=new MultiMovePilotController({artifact});await f.start();await f.submitMove(intent('e5d5'));assert.equal(f.retry(),true);assert.equal(f.getState().fen,artifact.initialFen);});
