#!/usr/bin/env python3
"""Snapshot PGN Mentor event/opening download names without exposing players."""
from __future__ import annotations

import hashlib
import json
import urllib.request
from datetime import datetime, timezone
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urlparse

ROOT = Path(__file__).resolve().parents[1]
SOURCE_PAGE = "https://www.pgnmentor.com/files.html"
CATALOG_PATH = ROOT / "data/pgn/pgnmentor-remote-catalog.json"
ALLOWLIST_PATH = ROOT / "api/pgn/pgnmentor-allowlist.js"
USER_AGENT = "CAISSA-Chess-PGN-Catalog/1.0 (+https://www.caissa-chess.org/)"
MAX_PAGE_BYTES = 4 * 1024 * 1024


class LinkCollector(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.events: set[str] = set()
        self.openings: set[str] = set()

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag.lower() != "a":
            return
        href = dict(attrs).get("href")
        if not href:
            return
        path = unquote(urlparse(href).path).lstrip("/")
        if path.startswith("events/") and path.lower().endswith(".pgn"):
            name = Path(path).name
            if name and name not in {".", ".."}:
                self.events.add(name)
        elif path.startswith("openings/") and path.lower().endswith(".zip"):
            name = Path(path).name
            if name and name not in {".", ".."}:
                self.openings.add(name)


def fetch_page() -> bytes:
    request = urllib.request.Request(
        SOURCE_PAGE,
        headers={"User-Agent": USER_AGENT, "Accept": "text/html,application/xhtml+xml"},
    )
    with urllib.request.urlopen(request, timeout=60) as response:
        declared = int(response.headers.get("Content-Length") or 0)
        if declared > MAX_PAGE_BYTES:
            raise RuntimeError("PGN Mentor index exceeds safety limit")
        data = response.read(MAX_PAGE_BYTES + 1)
    if len(data) > MAX_PAGE_BYTES:
        raise RuntimeError("PGN Mentor index exceeds safety limit")
    return data


def js_array(name: str, values: list[str]) -> str:
    body = ",\n".join(f"    {json.dumps(value)}" for value in values)
    return f"export const {name} = new Set([\n{body}\n]);\n"


def main() -> None:
    page = fetch_page()
    parser = LinkCollector()
    parser.feed(page.decode("utf-8", errors="replace"))
    events = sorted(parser.events, key=str.casefold)
    openings = sorted(parser.openings, key=str.casefold)
    if len(events) < 100:
        raise RuntimeError(f"unexpectedly small event catalog: {len(events)}")
    if len(openings) < 100:
        raise RuntimeError(f"unexpectedly small opening catalog: {len(openings)}")

    generated_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    digest = hashlib.sha256(page).hexdigest()
    catalog = {
        "schemaVersion": 1,
        "sourcePage": SOURCE_PAGE,
        "generatedAt": generated_at,
        "sourcePageSha256": digest,
        "playerDirectoryExposed": False,
        "policy": {
            "events": "remote-through-caissa-gateway",
            "openings": "remote-zip-through-caissa-gateway; indexed/paged consumption required before public opening UX",
            "players": "not-exposed; CAISSA uses physical player archives instead",
            "commercialRightsStatus": "unverified"
        },
        "eventCount": len(events),
        "openingCount": len(openings),
        "events": events,
        "openings": openings,
    }
    CATALOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CATALOG_PATH.write_text(json.dumps(catalog, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")

    js = "// Generated by scripts/update-pgnmentor-remote-catalog.py. Do not hand-edit.\n"
    js += js_array("PGN_MENTOR_EVENT_FILES", events)
    js += "\n"
    js += js_array("PGN_MENTOR_OPENING_FILES", openings)
    ALLOWLIST_PATH.write_text(js, encoding="utf-8", newline="\n")

    print(f"PGN Mentor remote catalog: {len(events)} events, {len(openings)} openings")
    print(f"Source page sha256={digest}")


if __name__ == "__main__":
    main()
