import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {PLAY_V2_BETA_STAGE_ENV,resolvePlayV2BetaEntry} from '../../js/play/play-v2-beta-entry-gate.js';import {createPlayBetaService} from '../../api/_lib/play-beta-service.js';
const read=path=>fs.readFileSync(new URL(`../../${path}`,import.meta.url),'utf8');const response=()=>({statusCode:200,headers:{},body:null,setHeader(k,v){this.headers[k]=v;},status(v){this.statusCode=v;return this;},json(v){this.body=v;return this;}});
test('PlayV2PublicBetaPolicy@1.0.0 is exact and frozen',()=>{const root={};vm.runInNewContext(read('js/play/play-v2-public-beta-policy.js'),{globalThis:root});const policy=root.CaissaPlayV2PublicBetaPolicy;assert.equal(policy.contractId,'PlayV2PublicBetaPolicy@1.0.0');assert.equal(policy.stage,'public-beta');assert.equal(policy.accountRequired,false);assert.equal(policy.analyticsTransport,'disabled');assert.equal(policy.fics,'excluded');assert.equal(policy.education,'excluded');assert.equal(policy.players,'unavailable');assert.ok(Object.isFrozen(policy));});
test('stage and route matrix is exact, case-sensitive, and fail-closed',()=>{for(const path of ['/play','/play/games','/play/bots','/play/coach'])assert.equal(resolvePlayV2BetaEntry(path,{[PLAY_V2_BETA_STAGE_ENV]:'public-beta'}).authorized,true,path);for(const stage of [undefined,'','disabled','internal','invite-only','PUBLIC-BETA','public-beta ','public'])assert.equal(resolvePlayV2BetaEntry('/play',{[PLAY_V2_BETA_STAGE_ENV]:stage}).authorized,false,String(stage));for(const path of ['/play/invite','/play/players','/play/qa/promotion','/play/qa/ipad-analyze-diagnostic','/play/qa/bug-diary','/play/','/play//bots'])assert.equal(resolvePlayV2BetaEntry(path,{[PLAY_V2_BETA_STAGE_ENV]:'public-beta'}).authorized,false,path);});
test('official document has no beta branding, invite, Supabase, FICS, education, analytics, or direct Discord resource',()=>{const html=read('play-v2-public-beta.html');assert.match(html,/data-caissa-play-v2-entry="official"/);assert.doesNotMatch(html,/Public Beta|discord\.gg\/g5vTsSrDA|play-v2-invite-client|invite-redemption|\/api\/play-beta\/(?:entry|redeem|session|status|logout)|SUPABASE_|caissa-clarity/i);assert.match(html,/js\/auth-config\.js/);assert.match(html,/js\/caissa-auth\.js/);assert.match(html,/rel="canonical" href="https:\/\/www\.caissa-chess\.org\/play"/);const resources=(html.match(/<(?:script|link)\b[^>]*>/gi)||[]).filter(item=>!/rel="canonical"/i.test(item));assert.equal(resources.some(item=>/https?:\/\/|discord|fics-client|academy/i.test(item)),false);assert.match(html,/connect-src 'self'[^;]*https:\/\/\*\.clerk\.accounts\.dev/);});
test('all historical invite APIs fail closed in public-beta without a store call',async()=>{let calls=0;const store=new Proxy({}, {get(){return async()=>{calls++;throw new Error('must not call');};}});const service=createPlayBetaService({store,env:{CAISSA_PLAY_V2_BETA_STAGE:'public-beta'}});for(const method of ['redeem','session','status','logout','feedback']){const res=response();await service[method]({method:method==='session'||method==='status'?'GET':'POST',headers:{}},res);assert.ok(res.statusCode>=400,method);}assert.equal(calls,0);});
test('server, middleware, and Vercel keep direct documents and invite route closed',()=>{const server=read('server.js'),middleware=read('middleware.js'),vercel=JSON.parse(read('vercel.json'));assert.match(server,/play-v2-public-beta\.html/);for(const source of ['/play-v2.html','/play-v2-public-beta.html','/play-v2-invite.html','/play-v2-promotion-qa.html','/play-v2-ipad-analyze-diagnostic.html']){assert.ok(vercel.rewrites.some(rule=>rule.source===source&&rule.destination==='/play-v2-unavailable.html'),source);assert.match(middleware,new RegExp(source.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));}assert.ok(vercel.rewrites.some(rule=>rule.source==='/play/beta/invite'&&rule.destination==='/play-v2-unavailable.html'));});
test('Vercel Hobby deployment uses middleware and retains only the twelve production API entrypoints',()=>{const middleware=read('middleware.js'),vercel=JSON.parse(read('vercel.json'));assert.match(middleware,/PLAY_V2_PUBLIC_BETA_DOCUMENT/);assert.equal(vercel.rewrites.some(rule=>String(rule.destination).startsWith('/api/play-beta/')),false);const historical=fs.readdirSync(new URL('../../history/play-v2-invite-only/api/play-beta/',import.meta.url)).filter(name=>name.endsWith('.js')).sort();assert.deepEqual(historical,['entry.js','feedback.js','logout.js','redeem.js','session.js','status.js']);assert.match(read('.vercelignore'),/^history\/\*\*$/m);});
